deployment:
  name: picture-api
  docker:
    image: artemek47/picture-api
    tag: latest
    secret: docker.secret
  resources:
    cpu: 100m
    memory: 250Mi
  repllicas: 1
  port: 5000

s3:
  secret: minio-creds
  host: minio-service
  port: 9000

app:
  host: '0.0.0.0'
  port: 5000
  s3:
    bucket:
      picture: hobbora-pictures
    default:
      path:
        profile: static/images/default_pfp.jpg
        hobby: static/images/default_hobby.webp
