apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.deployment.docker.secret }}
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.docker.image}}:{{$.Values.deployment.docker.tag}}
        ports:
        - containerPort: {{ .Values.deployment.port }}
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: S3_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.secret }}
              key: S3_USER
              optional: false
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.secret }}
              key: S3_ENDPOINT
              optional: false
        - name: S3_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.secret }}
              key: S3_PASS
              optional: false
        - name: PICTURE_BUCKET
          value: {{ .Values.app.s3.bucket.picture  | quote }}
        - name: DEFAULT_PROFILE_PIC_PATH
          value: {{ .Values.app.s3.default.path.profile  | quote }}
        - name: DEFAULT_HOBBY_PIC_PATH
          value: {{ .Values.app.s3.default.path.hobby  | quote }}
        - name: APP_PORT
          value: {{ .Values.app.port  | quote }}
        - name: APP_HOST
          value: {{ .Values.app.host  | quote }}
